title: 蒙古文信息处理
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://huangfeilong.cn/mitl/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
